# .gitlab-ci.yml

stages:
  - deploy

job_deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client rsync
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $VM_IP_ADDRESS >> ~/.ssh/known_hosts
  script:
    # Transfer the entire repository excluding unnecessary files
    - rsync -avz --delete --exclude '.git' --exclude 'build_output' . $VM_USER@$VM_IP_ADDRESS:/home/ubuntu/agisit24-g12/
    # SSH into the VM and execute commands
    - |
      ssh -o StrictHostKeyChecking=no $VM_USER@$VM_IP_ADDRESS "
        cd /home/ubuntu/agisit24-g12/ && \
        mvn clean package && \
        docker-compose build && \
        docker-compose up -d && \
        docker image prune -f && \
        docker container prune -f
      "
  only:
    - master
