apiVersion: skaffold/v2beta16
kind: Config
build:
  artifacts:
    - image: balancer
      context: ./balancer
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "target/*.jar"
            dest: "/app"

    - image: calendar-service
      context: ./calendar-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "target/calendar-service-0.0.1-SNAPSHOT.jar"
            dest: "/app"

    - image: mysql
      context: ./mysql
      docker:
        dockerfile: Dockerfile

    - image: user-service
      context: ./user-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "target/*.jar"
            dest: "/app"

    - image: auth-service
      context: ./auth-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "target/*.jar"
            dest: "/app"    

    - image: mgmt-service
      context: .
      docker:
        dockerfile: ./Dockerfile  

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
