server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/calendar_db
    username: calendar_user
    password: 4X+8a?qo4uLc
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
user-service:
  url: http://user-service:8080