apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: balancer
  name: balancer
spec:
  type: LoadBalancer  # Exposes the balancer service externally
  ports:
    - protocol: TCP
      port: 80          # Exposed external port
      targetPort: 80     # Internal Nginx port
      name: "http"
  selector:
    io.kompose.service: balancer  # Matches the pods with the 'balancer' label
status:
  loadBalancer: {}
