apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    io.kompose.service: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  template:
    metadata:
      labels:
        io.kompose.service: user-service
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  io.kompose.service: user-service
              topologyKey: "kubernetes.io/hostname"
      containers:
        - image: gcr.io/agisit-2425-website-1112951/user-service:latest
          name: user-service
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "calendar_db"
            - name: DB_USER
              value: "calendar_user"
            - name: DB_PASSWORD
              value: "4X+8a?qo4uLc"
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8080
          #   initialDelaySeconds: 30   # Delay before it starts checking
          #   periodSeconds: 10
          # # livenessProbe:
          # #   httpGet:
          # #     path: /actuator/health
          # #     port: 8080
          #   initialDelaySeconds: 30   # Delay for liveness check to prevent restarts
          #   periodSeconds: 10
          resources: {}
      restartPolicy: Always
